In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
orginal = pd.read_csv(r'C:\Users\Nikhil\Desktop\Data Science\income(1).csv', na_values=" ?")
df = orginal.copy()

In [3]:
print(df.isnull().sum())

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64


In [4]:
summary = df.describe(include='O')
summary

JobType    EdType        maritalstatus       occupation relationship  \
count      30169     31978                31978            30162        31978   
unique         8        16                    7               14            6   
top      Private   HS-grad   Married-civ-spouse   Prof-specialty      Husband   
freq       22286     10368                14692             4038        12947   

          race gender   nativecountry                        SalStat  
count    31978  31978           31978                          31978  
unique       5      2              41                              2  
top      White   Male   United-States   less than or equal to 50,000  
freq     27430  21370           29170                          24283

In [5]:
df = df.dropna(axis=0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30162 entries, 0 to 31977
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30162 non-null  int64 
 1   JobType        30162 non-null  object
 2   EdType         30162 non-null  object
 3   maritalstatus  30162 non-null  object
 4   occupation     30162 non-null  object
 5   relationship   30162 non-null  object
 6   race           30162 non-null  object
 7   gender         30162 non-null  object
 8   capitalgain    30162 non-null  int64 
 9   capitalloss    30162 non-null  int64 
 10  hoursperweek   30162 non-null  int64 
 11  nativecountry  30162 non-null  object
 12  SalStat        30162 non-null  object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB


In [7]:
df.columns

Index(['age', 'JobType', 'EdType', 'maritalstatus', 'occupation',
       'relationship', 'race', 'gender', 'capitalgain', 'capitalloss',
       'hoursperweek', 'nativecountry', 'SalStat'],
      dtype='object')

In [8]:
pd.crosstab(df['JobType'], df['maritalstatus'],margins=True, normalize=True)

maritalstatus       Divorced   Married-AF-spouse   Married-civ-spouse  \
JobType                                                                 
 Federal-gov        0.005504            0.000099             0.015317   
 Local-gov          0.012035            0.000000             0.033585   
 Private            0.102546            0.000497             0.316624   
 Self-emp-inc       0.003249            0.000000             0.026590   
 Self-emp-not-inc   0.009449            0.000066             0.054870   
 State-gov          0.006929            0.000033             0.019064   
 Without-pay        0.000000            0.000000             0.000265   
All                 0.139712            0.000696             0.466315   

maritalstatus       Married-spouse-absent   Never-married   Separated  \
JobType                                                                 
 Federal-gov                     0.000365        0.007957    0.000829   
 Local-gov                       0.000696        0.017373    0.001989   
 Private                         0.009449        0.266063    0.024567   
 Self-emp-inc                    0.000133        0.004045    0.000663   
 Self-emp-not-inc                0.001028        0.013295    0.001724   
 State-gov                       0.000564        0.013593    0.001359   
 Without-pay                     0.000033        0.000133    0.000000   
All                              0.012267        0.322459    0.031132   

maritalstatus       Widowed       All  
JobType                                
 Federal-gov       0.001194  0.031265  
 Local-gov         0.002851  0.068530  
 Private           0.019130  0.738877  
 Self-emp-inc      0.000928  0.035608  
 Self-emp-not-inc  0.002420  0.082853  
 State-gov         0.000862  0.042404  
 Without-pay       0.000033  0.000464  
All                0.027419  1.000000

In [9]:
np.unique(df['SalStat'])

array([' greater than 50,000', ' less than or equal to 50,000'],
      dtype=object)

In [10]:
pd.crosstab(index=df['gender'], columns=df['SalStat'], margins=True,normalize='index')

SalStat   greater than 50,000   less than or equal to 50,000
gender                                                      
 Female              0.113678                       0.886322
 Male                0.313837                       0.686163
All                  0.248922                       0.751078

In [11]:
df['SalStat'] = df['SalStat'].map({' less than or equal to 50,000':0, ' greater than 50,000':1})
df['SalStat'].value_counts()

0    22654
1     7508
Name: SalStat, dtype: int64

In [12]:
new_df = pd.get_dummies(df, drop_first=True)
new_df

age  capitalgain  capitalloss  hoursperweek  SalStat  \
0       45            0            0            28        0   
1       24            0            0            40        0   
2       44            0            0            40        1   
3       27            0            0            40        0   
4       20            0            0            35        0   
...    ...          ...          ...           ...      ...   
31973   34          594            0            60        0   
31974   34            0            0            40        0   
31975   23            0            0            40        0   
31976   42            0            0            40        0   
31977   29            0            0            40        0   

       JobType_ Local-gov  JobType_ Private  JobType_ Self-emp-inc  \
0                       0                 1                      0   
1                       0                 0                      0   
2                       0                 1                      0   
3                       0                 1                      0   
4                       0                 1                      0   
...                   ...               ...                    ...   
31973                   1                 0                      0   
31974                   1                 0                      0   
31975                   0                 1                      0   
31976                   1                 0                      0   
31977                   0                 1                      0   

       JobType_ Self-emp-not-inc  JobType_ State-gov  ...  \
0                              0                   0  ...   
1                              0                   0  ...   
2                              0                   0  ...   
3                              0                   0  ...   
4                              0                   0  ...   
...                          ...                 ...  ...   
31973                          0                   0  ...   
31974                          0                   0  ...   
31975                          0                   0  ...   
31976                          0                   0  ...   
31977                          0                   0  ...   

       nativecountry_ Portugal  nativecountry_ Puerto-Rico  \
0                            0                           0   
1                            0                           0   
2                            0                           0   
3                            0                           0   
4                            0                           0   
...                        ...                         ...   
31973                        0                           0   
31974                        0                           0   
31975                        0                           0   
31976                        0                           0   
31977                        0                           0   

       nativecountry_ Scotland  nativecountry_ South  nativecountry_ Taiwan  \
0                            0                     0                      0   
1                            0                     0                      0   
2                            0                     0                      0   
3                            0                     0                      0   
4                            0                     0                      0   
...                        ...                   ...                    ...   
31973                        0                     0                      0   
31974                        0                     0                      0   
31975                        0                     0                      0   
31976                        0                     0                      0   
31977                        0                     0          

In [13]:
column_list = list(new_df.columns)
column_list

['age',
 'capitalgain',
 'capitalloss',
 'hoursperweek',
 'SalStat',
 'JobType_ Local-gov',
 'JobType_ Private',
 'JobType_ Self-emp-inc',
 'JobType_ Self-emp-not-inc',
 'JobType_ State-gov',
 'JobType_ Without-pay',
 'EdType_ 11th',
 'EdType_ 12th',
 'EdType_ 1st-4th',
 'EdType_ 5th-6th',
 'EdType_ 7th-8th',
 'EdType_ 9th',
 'EdType_ Assoc-acdm',
 'EdType_ Assoc-voc',
 'EdType_ Bachelors',
 'EdType_ Doctorate',
 'EdType_ HS-grad',
 'EdType_ Masters',
 'EdType_ Preschool',
 'EdType_ Prof-school',
 'EdType_ Some-college',
 'maritalstatus_ Married-AF-spouse',
 'maritalstatus_ Married-civ-spouse',
 'maritalstatus_ Married-spouse-absent',
 'maritalstatus_ Never-married',
 'maritalstatus_ Separated',
 'maritalstatus_ Widowed',
 'occupation_ Armed-Forces',
 'occupation_ Craft-repair',
 'occupation_ Exec-managerial',
 'occupation_ Farming-fishing',
 'occupation_ Handlers-cleaners',
 'occupation_ Machine-op-inspct',
 'occupation_ Other-service',
 'occupation_ Priv-house-serv',
 'occupation_ Pr

In [14]:
features = list(set(column_list) - set(['SalStat']))
features

['EdType_ 1st-4th',
 'occupation_ Tech-support',
 'EdType_ HS-grad',
 'nativecountry_ Honduras',
 'nativecountry_ Hungary',
 'EdType_ 12th',
 'occupation_ Farming-fishing',
 'nativecountry_ England',
 'JobType_ Local-gov',
 'nativecountry_ Thailand',
 'relationship_ Other-relative',
 'nativecountry_ Guatemala',
 'nativecountry_ Germany',
 'EdType_ Assoc-voc',
 'maritalstatus_ Never-married',
 'race_ Black',
 'nativecountry_ Greece',
 'race_ White',
 'nativecountry_ Italy',
 'gender_ Male',
 'occupation_ Protective-serv',
 'nativecountry_ Japan',
 'hoursperweek',
 'occupation_ Other-service',
 'nativecountry_ United-States',
 'nativecountry_ Laos',
 'maritalstatus_ Married-spouse-absent',
 'occupation_ Sales',
 'occupation_ Exec-managerial',
 'nativecountry_ Columbia',
 'maritalstatus_ Married-civ-spouse',
 'nativecountry_ South',
 'occupation_ Transport-moving',
 'nativecountry_ Cuba',
 'maritalstatus_ Widowed',
 'nativecountry_ Philippines',
 'occupation_ Priv-house-serv',
 'nativecou

In [16]:
y = new_df['SalStat'].values
y

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [17]:
x = new_df[features].values
x

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [44]:
train_x, test_x, train_y, test_y = train_test_split(x,y,test_size=0.1,random_state=0)
# test_y = list(test_y)
type(test_y)

numpy.ndarray

In [45]:
logistic = LogisticRegression(max_iter=10000)

In [46]:
logistic.fit(train_x, train_y)
logistic.intercept_

array([-3.52275765])

In [47]:
prediction = (logistic.predict(test_x))
type(prediction)

numpy.ndarray

In [48]:
confus = confusion_matrix(test_y, prediction)
confus

array([[2100,  150],
       [ 319,  448]], dtype=int64)

In [49]:
print(classification_report(test_y, prediction))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90      2250
           1       0.75      0.58      0.66       767

    accuracy                           0.84      3017
   macro avg       0.81      0.76      0.78      3017
weighted avg       0.84      0.84      0.84      3017



In [52]:
logistic.score(train_x, train_y)

0.8477804383864431

In [53]:
temp_df = df[column_list - set(["age"], ["maritalstatus"], ["relationship"], ["capitalgain"], ["capitalloss"], ["hoursperweek"], ["nativecountry"], ["SalStat"])]
new_df1 = pd.get_dummies(temp_df, drop_first=True)
new_df1

TypeError: set expected at most 1 argument, got 8